"""Special actions — jokes, proverbs, music tracks, breathing exercises."""
import random
from app.models.schemas import EmotionType, MoodLevel, MusicTrack

EMOTION_JOKES = {
    EmotionType.ANGRY: ["Why do cows wear bells? Because their horns don't work! 🐄 (See? Even cows have things that don't work — and they're still mooing along just fine.)", "I was going to tell a joke about anger... but I decided to let it go. 😄 (Letting go is actually the superpower here.)", "What do you call a sleeping dinosaur? A dino-snore! 🦕 (Your anger is valid — but even T-Rexes needed rest.)", "Why don't scientists trust atoms? Because they make up everything! ⚛️ (Unlike your feelings — those are 100% real and valid.)", "I told my anger to take a hike. It said 'Fine!' and stormed off. 😂"],
    EmotionType.STRESSED: ["Why did the scarecrow win an award? Because he was outstanding in his field! 🌾 (Just like you — even on tough days, you're still showing up.)", "Why did the bicycle fall over? Because it was two-tired! 🚲 (Rest is valid — even bikes need breaks.)", "What do you call cheese that isn't yours? Nacho cheese! 🧀 (And that problem stressing you out? Maybe it's nacho problem either.)", "I'm reading a book about anti-gravity. It's impossible to put down! 📚 (Just like your resilience — impossible to keep down.)"],
    EmotionType.ANXIOUS: ["Why can't you give Elsa a balloon? Because she'll let it go! ❄️ (Letting go of worry is actually a superpower.)", "What did the ocean say to the beach? Nothing, it just waved! 🌊 (Sometimes a simple wave hello to yourself is enough.)", "Why did the coffee file a police report? It got mugged! ☕ (Hang in there — your day is about to get better.)"],
    EmotionType.SAD: ["Why don't scientists trust atoms? Because they make up everything! 😂 (Unlike your sadness — that's real and it deserves space.)", "What do you call a bear with no teeth? A gummy bear! 🐻 (Sweet, just like you deserve to feel today.)", "I told my therapist I was having trouble letting go of the past. She said 'We'll work on it.' I said 'Same thing she said last week.' 😄"],
    EmotionType.LONELY: ["Why did the tomato turn red? Because it saw the salad dressing! 🍅 (Even vegetables have awkward social moments.)", "What do you call a fish without eyes? A fsh! 🐟 (Sometimes we all feel a little lost — that's okay.)", "I asked my dog what 2 minus 2 is. He said nothing. 🐶 (You're never truly alone when you have moments like these.)"],
    EmotionType.OVERWHELMED: ["Why did the math book look so sad? Because it had too many problems! 📚 (Relatable. But you only need to solve one today.)", "What do you call a pile of cats? A meowtain! 🐱 (Even mountains are climbed one step at a time.)", "I tried to write a joke about procrastination... I'll finish it later. 😄 (One thing at a time — that's all you need.)"],
    EmotionType.NEUTRAL: ["Why don't eggs tell jokes? They'd crack each other up! 🥚 (A little crack of humor never hurt anyone.)", "What do you call a sleeping dinosaur? A dino-snore! 🦕 (Even neutral days deserve a smile.)", "Why did the calendar go to therapy? It had too many dates! 📅 (We all need a little help sometimes.)"],
    EmotionType.HAPPY: ["Why did the sun go to school? To get a little brighter! ☀️ (Just like you — already bright, always growing.)", "What do you call a happy cowboy? A jolly rancher! 🤠 (Keep that energy going!)"],
    EmotionType.EXCITED: ["Why did the bicycle keep falling over? It was two-tired of standing still! 🚲 (Unlike you — you're full of energy!)", "What do you call an excited dog? A wagaholic! 🐕 (Channel that excitement into something amazing.)"],
    EmotionType.CALM: ["Why did the Zen master refuse anesthesia? He wanted to transcend dental medication! 🧘 (A little calm humor for a calm moment.)", "What do you call a peaceful bee? A calm-omile! 🌼 (Savoring this calm is exactly right.)"],
}

EMOTION_PROVERBS = {
    EmotionType.ANGRY: [("For every minute you remain angry, you give up sixty seconds of peace of mind.", "Ralph Waldo Emerson"), ("Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.", "Mark Twain"), ("You will not be punished for your anger, you will be punished by your anger.", "Buddha"), ("The greatest remedy for anger is delay.", "Seneca")],
    EmotionType.STRESSED: [("You don't have to control your thoughts. You just have to stop letting them control you.", "Dan Millman"), ("The greatest weapon against stress is our ability to choose one thought over another.", "William James"), ("Almost everything will work again if you unplug it for a few minutes, including you.", "Anne Lamott"), ("Stress is not what happens to us. It's our response to what happens.", "Maureen Killoran")],
    EmotionType.ANXIOUS: [("Nothing diminishes anxiety faster than action.", "Walter Anderson"), ("You don't have to see the whole staircase, just take the first step.", "Martin Luther King Jr."), ("Worry does not empty tomorrow of its sorrow, it empties today of its strength.", "Corrie Ten Boom"), ("Present-moment focus is the antidote to anxiety.", "Dr. Daniel Siegel")],
    EmotionType.SAD: [("Even the darkest night will end and the sun will rise.", "Victor Hugo"), ("The wound is the place where the Light enters you.", "Rumi"), ("Tears are words that need to be written.", "Paulo Coelho"), ("You are allowed to be both a masterpiece and a work in progress simultaneously.", "Sophia Bush")],
    EmotionType.LONELY: [("Connection is why we're here. It is what gives purpose and meaning to our lives.", "Brené Brown"), ("The cure for loneliness is not more people — it's deeper connection.", "Dr. Vivek Murthy, US Surgeon General"), ("Loneliness is the poverty of self; solitude is the richness of self.", "May Sarton"), ("The most terrible poverty is loneliness, and the feeling of being unloved.", "Mother Teresa")],
    EmotionType.OVERWHELMED: [("You don't have to do it all. You just have to do the next right thing.", "Glennon Doyle"), ("It's not the load that breaks you down, it's the way you carry it.", "Lou Holtz"), ("The key is not to prioritize what's on your schedule, but to schedule your priorities.", "Stephen Covey")],
    EmotionType.HAPPY: [("Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"), ("The purpose of our lives is to be happy.", "Dalai Lama"), ("Joy is not in things; it is in us.", "Richard Wagner")],
    EmotionType.CALM: [("Calm mind brings inner strength and self-confidence.", "Dalai Lama"), ("In the midst of movement and chaos, keep stillness inside of you.", "Deepak Chopra"), ("Serenity is not freedom from the storm, but peace amid the storm.", "Unknown")],
    EmotionType.EXCITED: [("Enthusiasm is the electricity of life.", "Gordon Parks"), ("Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson")],
    EmotionType.NEUTRAL: [("The present moment is the only moment available to us, and it is the door to all moments.", "Thich Nhat Hanh"), ("Awareness is the greatest agent for change.", "Eckhart Tolle"), ("Between stimulus and response there is a space. In that space is our power to choose our response.", "Viktor Frankl")],
}

MUSIC_TRACKS = {
    EmotionType.STRESSED: [MusicTrack(title="Weightless", artist="Marconi Union", spotify_url="https://open.spotify.com/search/Weightless%20Marconi%20Union", youtube_url="https://www.youtube.com/results?search_query=Weightless+Marconi+Union", reason="Scientifically proven to reduce anxiety by 65%"), MusicTrack(title="Gymnopédie No.1", artist="Erik Satie", spotify_url="https://open.spotify.com/search/Gymnopedie%20No.1%20Satie", youtube_url="https://www.youtube.com/results?search_query=Gymnopedie+No+1+Satie", reason="Slow, simple, instantly calming"), MusicTrack(title="Lofi Hip Hop Radio", artist="Various Artists", spotify_url="https://open.spotify.com/playlist/0vvXsWCC9xrXsKd4eZs8YY", youtube_url="https://www.youtube.com/results?search_query=lofi+hip+hop+radio+beats+to+relax", reason="60-80 BPM naturally syncs your heart rate down")],
    EmotionType.ANXIOUS: [MusicTrack(title="Clair de Lune", artist="Claude Debussy", spotify_url="https://open.spotify.com/search/Clair%20de%20Lune%20Debussy", youtube_url="https://www.youtube.com/results?search_query=Clair+de+Lune+Debussy", reason="Gentle, flowing — like water for your nervous system"), MusicTrack(title="Rain Sounds 1 Hour", artist="Nature Sounds", spotify_url="https://open.spotify.com/search/rain%20sounds%20sleep", youtube_url="https://www.youtube.com/results?search_query=rain+sounds+1+hour+sleep", reason="Natural patterns tell your brain 'everything is safe'"), MusicTrack(title="432Hz Healing Frequency", artist="Healing Music", spotify_url="https://open.spotify.com/search/432hz%20healing%20frequency", youtube_url="https://www.youtube.com/results?search_query=432hz+healing+frequency+music", reason="Many people find this frequency deeply grounding")],
    EmotionType.SAD: [MusicTrack(title="The Night We Met", artist="Lord Huron", spotify_url="https://open.spotify.com/search/The%20Night%20We%20Met%20Lord%20Huron", youtube_url="https://www.youtube.com/results?search_query=The+Night+We+Met+Lord+Huron", reason="Meets you where you are — validating, not dismissive"), MusicTrack(title="Here Comes the Sun", artist="The Beatles", spotify_url="https://open.spotify.com/search/Here%20Comes%20the%20Sun%20Beatles", youtube_url="https://www.youtube.com/results?search_query=Here+Comes+the+Sun+Beatles", reason="One of the most mood-lifting songs ever recorded"), MusicTrack(title="Fix You", artist="Coldplay", spotify_url="https://open.spotify.com/search/Fix%20You%20Coldplay", youtube_url="https://www.youtube.com/results?search_query=Fix+You+Coldplay", reason="For when you need to feel held and understood")],
    EmotionType.ANGRY: [MusicTrack(title="Moonlight Sonata", artist="Beethoven", spotify_url="https://open.spotify.com/search/Moonlight%20Sonata%20Beethoven", youtube_url="https://www.youtube.com/results?search_query=Moonlight+Sonata+Beethoven", reason="Intense but controlled — matches your energy without escalating"), MusicTrack(title="Mad World", artist="Gary Jules", spotify_url="https://open.spotify.com/search/Mad%20World%20Gary%20Jules", youtube_url="https://www.youtube.com/results?search_query=Mad+World+Gary+Jules", reason="Acknowledges the feeling without feeding the anger"), MusicTrack(title="Peaceful Piano", artist="Spotify Playlist", spotify_url="https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO", youtube_url="https://www.youtube.com/results?search_query=peaceful+piano+music+calm", reason="No lyrics, lets your mind settle after the storm")],
    EmotionType.OVERWHELMED: [MusicTrack(title="Gymnopédie No.1", artist="Erik Satie", spotify_url="https://open.spotify.com/search/Gymnopedie%20No.1%20Satie", youtube_url="https://www.youtube.com/results?search_query=Gymnopedie+No+1+Satie", reason="Minimal, slow — reduces cognitive load immediately"), MusicTrack(title="Weightless", artist="Marconi Union", spotify_url="https://open.spotify.com/search/Weightless%20Marconi%20Union", youtube_url="https://www.youtube.com/results?search_query=Weightless+Marconi+Union", reason="Proven to reduce mental activity and overwhelm"), MusicTrack(title="Study Music No Lyrics", artist="Focus Music", spotify_url="https://open.spotify.com/search/study%20music%20no%20lyrics", youtube_url="https://www.youtube.com/results?search_query=study+music+no+lyrics+calm", reason="Background music under 80 BPM reduces mental noise")],
    EmotionType.LONELY: [MusicTrack(title="You've Got a Friend", artist="James Taylor", spotify_url="https://open.spotify.com/search/You've%20Got%20a%20Friend%20James%20Taylor", youtube_url="https://www.youtube.com/results?search_query=You've+Got+a+Friend+James+Taylor", reason="Warm, comforting — like a hug in song form"), MusicTrack(title="Count on Me", artist="Bruno Mars", spotify_url="https://open.spotify.com/search/Count%20on%20Me%20Bruno%20Mars", youtube_url="https://www.youtube.com/results?search_query=Count+on+Me+Bruno+Mars", reason="About friendship and showing up for each other"), MusicTrack(title="Lean on Me", artist="Bill Withers", spotify_url="https://open.spotify.com/search/Lean%20on%20Me%20Bill%20Withers", youtube_url="https://www.youtube.com/results?search_query=Lean+on+Me+Bill+Withers", reason="A reminder that everyone needs someone")],
    EmotionType.HAPPY: [MusicTrack(title="Happy", artist="Pharrell Williams", spotify_url="https://open.spotify.com/search/Happy%20Pharrell%20Williams", youtube_url="https://www.youtube.com/results?search_query=Happy+Pharrell+Williams", reason="A classic for a reason — pure joy"), MusicTrack(title="Can't Stop the Feeling", artist="Justin Timberlake", spotify_url="https://open.spotify.com/search/Can't%20Stop%20the%20Feeling%20Justin%20Timberlake", youtube_url="https://www.youtube.com/results?search_query=Can't+Stop+the+Feeling+Justin+Timberlake", reason="Amplify this good mood — you deserve it"), MusicTrack(title="Uptown Funk", artist="Bruno Mars", spotify_url="https://open.spotify.com/search/Uptown%20Funk%20Bruno%20Mars", youtube_url="https://www.youtube.com/results?search_query=Uptown+Funk+Bruno+Mars", reason="Impossible not to smile — celebrate this feeling")],
    EmotionType.CALM: [MusicTrack(title="432Hz Healing Frequency", artist="Healing Music", spotify_url="https://open.spotify.com/search/432hz%20healing%20frequency", youtube_url="https://www.youtube.com/results?search_query=432hz+healing+frequency", reason="Deepen this calm state with healing frequencies"), MusicTrack(title="Tibetan Singing Bowls", artist="Meditation Music", spotify_url="https://open.spotify.com/search/tibetan%20singing%20bowls", youtube_url="https://www.youtube.com/results?search_query=tibetan+singing+bowls+meditation", reason="Deeply meditative and grounding"), MusicTrack(title="Music for Airports", artist="Brian Eno", spotify_url="https://open.spotify.com/search/Music%20for%20Airports%20Brian%20Eno", youtube_url="https://www.youtube.com/results?search_query=Music+for+Airports+Brian+Eno", reason="Ambient, spacious, beautiful — perfect for reflection")],
    EmotionType.EXCITED: [MusicTrack(title="Eye of the Tiger", artist="Survivor", spotify_url="https://open.spotify.com/search/Eye%20of%20the%20Tiger%20Survivor", youtube_url="https://www.youtube.com/results?search_query=Eye+of+the+Tiger+Survivor", reason="Classic motivation — channel this energy"), MusicTrack(title="Lose Yourself", artist="Eminem", spotify_url="https://open.spotify.com/search/Lose%20Yourself%20Eminem", youtube_url="https://www.youtube.com/results?search_query=Lose+Yourself+Eminem", reason="Pure focused energy"), MusicTrack(title="Run the World", artist="Beyoncé", spotify_url="https://open.spotify.com/search/Run%20the%20World%20Beyonce", youtube_url="https://www.youtube.com/results?search_query=Run+the+World+Beyonce", reason="Confidence and power — match your excitement")],
    EmotionType.NEUTRAL: [MusicTrack(title="Viva la Vida", artist="Coldplay", spotify_url="https://open.spotify.com/search/Viva%20la%20Vida%20Coldplay", youtube_url="https://www.youtube.com/results?search_query=Viva+la+Vida+Coldplay", reason="Uplifting and cinematic — gently shifts a neutral mood"), MusicTrack(title="Dog Days Are Over", artist="Florence + The Machine", spotify_url="https://open.spotify.com/search/Dog%20Days%20Are%20Over%20Florence", youtube_url="https://www.youtube.com/results?search_query=Dog+Days+Are+Over+Florence+Machine", reason="Builds energy gradually — perfect for a neutral day"), MusicTrack(title="Mood Booster Playlist", artist="Spotify", spotify_url="https://open.spotify.com/search/mood%20booster", youtube_url="https://www.youtube.com/results?search_query=mood+booster+playlist", reason="Gently uplifting without being overwhelming")],
}

BREATHING_EXERCISES = [
    {"name": "4-7-8 Breathing", "steps": "1️⃣ Breathe IN through your nose for **4 counts**\n2️⃣ HOLD your breath for **7 counts**\n3️⃣ Breathe OUT through your mouth for **8 counts**\n🔄 Repeat 4 times", "benefit": "Activates your parasympathetic nervous system — your body's built-in calm switch. Works within 2 minutes."},
    {"name": "Box Breathing", "steps": "1️⃣ Breathe IN for **4 counts**\n2️⃣ HOLD for **4 counts**\n3️⃣ Breathe OUT for **4 counts**\n4️⃣ HOLD for **4 counts**\n🔄 Repeat 5-6 times", "benefit": "Used by Navy SEALs to stay calm under extreme pressure. Resets your nervous system fast."},
    {"name": "Physiological Sigh", "steps": "1️⃣ Take a deep breath IN through your nose\n2️⃣ At the top, take one more SHORT sniff IN\n3️⃣ Exhale SLOWLY and completely through your mouth\n🔄 Repeat 3 times", "benefit": "Stanford neuroscientists found this works in under 30 seconds — the fastest stress relief known."},
]


def get_joke(emotion: EmotionType) -> str:
    jokes = EMOTION_JOKES.get(emotion, EMOTION_JOKES[EmotionType.NEUTRAL])
    return random.choice(jokes)


def get_proverb(emotion: EmotionType) -> tuple[str, str]:
    proverbs = EMOTION_PROVERBS.get(emotion, EMOTION_PROVERBS[EmotionType.NEUTRAL])
    return random.choice(proverbs)


def get_music_tracks(emotion: EmotionType) -> list[MusicTrack]:
    tracks = list(MUSIC_TRACKS.get(emotion, MUSIC_TRACKS[EmotionType.NEUTRAL]))
    random.shuffle(tracks)
    return tracks[:3]


def get_special_action(emotion: EmotionType, mood_level: MoodLevel) -> tuple[str | None, str | None]:
    distress = {EmotionType.ANXIOUS, EmotionType.STRESSED, EmotionType.OVERWHELMED, EmotionType.ANGRY}
    if emotion in distress and mood_level in {MoodLevel.VERY_BAD, MoodLevel.BAD}:
        ex = random.choice(BREATHING_EXERCISES)
        return "breathing_exercise", f"**{ex['name']}**\n\n{ex['steps']}\n\n💡 *Why this works:* {ex['benefit']}"
    return None, None
